# Non-Mod-Specific Properties
modLoader = "javafml"
loaderVersion = "[44,)"
license = "GNU General Public License v3.0"
issueTrackerURL = "https://github.com/ShadowGry/copper-tools/issues"

# Mod Properties
[[mods]]
	modId = "coppertools"
	version = "${file.jarVersion}"
	displayName = "Copper Tools"
	updateJSONURL = "https://raw.githubusercontent.com/ShadowGry/copper-tools/HEAD/update.json"
	displayURL = "https://github.com/ShadowGry/copper-tools"
	#logoFile = ""
	authors = "ShadowGry"
	description = "Adds copper tools and armor that oxidize over time."

# Dependency Configurations
[[dependencies.coppertools]]
	modId = "forge"
	mandatory = true
	versionRange = "[44,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.coppertools]]
	modId = "minecraft"
	mandatory = true
	versionRange = "[1.19.3,1.20)"
	ordering = "NONE"
	side = "BOTH"
